<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-13VKMES" ignored="0" name="Test" tests="7" failures="1" timestamp="2021-09-22T12:14:10 IST" time="0.066" errors="0">
  <testcase name="password" time="0.01" classname="com.testngfeatures.Retry_Transform_Concept">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.001" classname="com.testngfeatures.Retry_Transform_Concept">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.002" classname="com.testngfeatures.Retry_Transform_Concept">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.002" classname="com.testngfeatures.Retry_Transform_Concept">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.001" classname="com.testngfeatures.Retry_Transform_Concept">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.001" classname="com.testngfeatures.Retry_Transform_Concept">
    <failure type="java.lang.AssertionError" message="expected [123] but found [456]">
      <![CDATA[java.lang.AssertionError: expected [123] but found [456]
at com.testngfeatures.Retry_Transform_Concept.password(Retry_Transform_Concept.java:27)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- password -->
  <testcase name="username" time="0.001" classname="com.testngfeatures.Retry_Transform_Concept"/>
</testsuite> <!-- Test -->
